### ISSUE TITLE
Broken 

### ISSUE THREAD

**Issue by letmaik** [rkh/travis-encrypt#1]
Always says "Message too long for RSA" no matter how long the input is.

**Comment by nabijaczleweli** [comment]
[Norepro, but close enough](http://imgur.com/a/Xs5A5)
(`<input>` exploded in size for clarity)

**Comment by letmaik** [comment]
Sorry, should have given the example I used:

![capture](https://cloud.githubusercontent.com/assets/530988/9959311/2871816e-5e13-11e5-8def-5fd64d97496a.PNG)

Tested with Firefox and Chrome.

**Comment by nabijaczleweli** [comment]
Interesting, doesn't work for me on that repo, neither (Firefox Developer Edition 42.0a2 (2015-08-24), but I doubt the browser's the culprit).

@neothemachine Browser versions, please?

**Comment by nabijaczleweli** [comment]
It _does_ look like a problem with slug length: try to encrypt a string of any length for [this](https://travis-ci.org/nabijaczleweli/01234567890123456789012345678901234567890123456789012345678901234567890123456789/builds/81009413) test repo (slug in build output for convenience)

**Comment by letmaik** [comment]
Firefox 40.0.3 and Chrome 45

Your repo example doesn't work either. I tried with "rkh/travis-encrypt" and it works. So there's a bug somewhere.

**Comment by nabijaczleweli** [comment]
As said above: it's a problem with slug length being too long for `travis-encrypt` to handle

**Comment by axel3rd** [comment]
Same problem for my repositories. Pity ... very nice feature for encrypt Travis password without install Ruby & CLI :-(

**Comment by rkh** [comment]
FWIW, this isn't a fix, but you should be able to set secure env vars via the Travis UI now (repository settings).

**Comment by slodki** [comment]
This bug can be easily fixed :heavy_check_mark: with my patch #3. You can test :mag: [fixed version](https://slodki.github.io/travis-encrypt/public/) online.

**Comment by slodki** [comment]
Fix for travis-ci/travis-ci#913 (still visible at @sinatra /sinatra repo, @travis-ci should check this old key) is ready as #5.

It's interesting how [Travis CLI handles](https://github.com/travis-ci/travis.rb/blob/master/lib/travis/tools/ssl_key.rb#L13) such keys [not generating OpenSSL errors](https://travis-ci.org/tslodki/test76/builds/176818710).
